apiVersion: apps/v1
kind: Deployment
metadata:
  name: tower-defense-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tower-defense-game
  template:
    metadata:
      labels:
        app: tower-defense-game
    spec:
      containers:
        - name: tower-defense-game
          image: tower-defense-game  # Nombre de la imagen de tu aplicación
          ports:
            - containerPort: 8080    # Puerto en el que tu aplicación escucha dentro del contenedor
